
package mythtvapi.dvr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Dvr", targetNamespace = "http://mythtv.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Dvr {


    /**
     * GET 
     * 
     * @param chanId
     * @param startTime
     * @param neverRecord
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddDontRecordSchedule", action = "http://mythtv.org/Dvr/AddDontRecordSchedule")
    @WebResult(name = "AddDontRecordScheduleResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "AddDontRecordSchedule", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.AddDontRecordSchedule")
    @ResponseWrapper(localName = "AddDontRecordScheduleResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.AddDontRecordScheduleResponse")
    public Boolean addDontRecordSchedule(
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "NeverRecord", targetNamespace = "http://mythtv.org")
        Boolean neverRecord);

    /**
     * POST 
     * 
     * @param autoMetaLookup
     * @param endOffset
     * @param findDay
     * @param description
     * @param dupMethod
     * @param episode
     * @param preferredInput
     * @param title
     * @param type
     * @param seriesId
     * @param inactive
     * @param inetref
     * @param station
     * @param autoTranscode
     * @param season
     * @param transcoder
     * @param startTime
     * @param chanId
     * @param findTime
     * @param searchType
     * @param recGroup
     * @param autoExpire
     * @param maxNewest
     * @param autoUserJob3
     * @param autoUserJob4
     * @param parentId
     * @param storageGroup
     * @param playGroup
     * @param filter
     * @param autoUserJob1
     * @param startOffset
     * @param autoUserJob2
     * @param maxEpisodes
     * @param recProfile
     * @param subtitle
     * @param endTime
     * @param category
     * @param dupIn
     * @param autoCommflag
     * @param programId
     * @param recPriority
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "AddRecordSchedule", action = "http://mythtv.org/Dvr/AddRecordSchedule")
    @WebResult(name = "AddRecordScheduleResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "AddRecordSchedule", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.AddRecordSchedule")
    @ResponseWrapper(localName = "AddRecordScheduleResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.AddRecordScheduleResponse")
    public Long addRecordSchedule(
        @WebParam(name = "Title", targetNamespace = "http://mythtv.org")
        String title,
        @WebParam(name = "Subtitle", targetNamespace = "http://mythtv.org")
        String subtitle,
        @WebParam(name = "Description", targetNamespace = "http://mythtv.org")
        String description,
        @WebParam(name = "Category", targetNamespace = "http://mythtv.org")
        String category,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar endTime,
        @WebParam(name = "SeriesId", targetNamespace = "http://mythtv.org")
        String seriesId,
        @WebParam(name = "ProgramId", targetNamespace = "http://mythtv.org")
        String programId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "Station", targetNamespace = "http://mythtv.org")
        String station,
        @WebParam(name = "FindDay", targetNamespace = "http://mythtv.org")
        Integer findDay,
        @WebParam(name = "FindTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar findTime,
        @WebParam(name = "ParentId", targetNamespace = "http://mythtv.org")
        Integer parentId,
        @WebParam(name = "Inactive", targetNamespace = "http://mythtv.org")
        Boolean inactive,
        @WebParam(name = "Season", targetNamespace = "http://mythtv.org")
        Long season,
        @WebParam(name = "Episode", targetNamespace = "http://mythtv.org")
        Long episode,
        @WebParam(name = "Inetref", targetNamespace = "http://mythtv.org")
        String inetref,
        @WebParam(name = "Type", targetNamespace = "http://mythtv.org")
        String type,
        @WebParam(name = "SearchType", targetNamespace = "http://mythtv.org")
        String searchType,
        @WebParam(name = "RecPriority", targetNamespace = "http://mythtv.org")
        Integer recPriority,
        @WebParam(name = "PreferredInput", targetNamespace = "http://mythtv.org")
        Long preferredInput,
        @WebParam(name = "StartOffset", targetNamespace = "http://mythtv.org")
        Integer startOffset,
        @WebParam(name = "EndOffset", targetNamespace = "http://mythtv.org")
        Integer endOffset,
        @WebParam(name = "DupMethod", targetNamespace = "http://mythtv.org")
        String dupMethod,
        @WebParam(name = "DupIn", targetNamespace = "http://mythtv.org")
        String dupIn,
        @WebParam(name = "Filter", targetNamespace = "http://mythtv.org")
        Long filter,
        @WebParam(name = "RecProfile", targetNamespace = "http://mythtv.org")
        String recProfile,
        @WebParam(name = "RecGroup", targetNamespace = "http://mythtv.org")
        String recGroup,
        @WebParam(name = "StorageGroup", targetNamespace = "http://mythtv.org")
        String storageGroup,
        @WebParam(name = "PlayGroup", targetNamespace = "http://mythtv.org")
        String playGroup,
        @WebParam(name = "AutoExpire", targetNamespace = "http://mythtv.org")
        Boolean autoExpire,
        @WebParam(name = "MaxEpisodes", targetNamespace = "http://mythtv.org")
        Integer maxEpisodes,
        @WebParam(name = "MaxNewest", targetNamespace = "http://mythtv.org")
        Boolean maxNewest,
        @WebParam(name = "AutoCommflag", targetNamespace = "http://mythtv.org")
        Boolean autoCommflag,
        @WebParam(name = "AutoTranscode", targetNamespace = "http://mythtv.org")
        Boolean autoTranscode,
        @WebParam(name = "AutoMetaLookup", targetNamespace = "http://mythtv.org")
        Boolean autoMetaLookup,
        @WebParam(name = "AutoUserJob1", targetNamespace = "http://mythtv.org")
        Boolean autoUserJob1,
        @WebParam(name = "AutoUserJob2", targetNamespace = "http://mythtv.org")
        Boolean autoUserJob2,
        @WebParam(name = "AutoUserJob3", targetNamespace = "http://mythtv.org")
        Boolean autoUserJob3,
        @WebParam(name = "AutoUserJob4", targetNamespace = "http://mythtv.org")
        Boolean autoUserJob4,
        @WebParam(name = "Transcoder", targetNamespace = "http://mythtv.org")
        Integer transcoder);

    /**
     * POST 
     * 
     * @param forceDelete
     * @param chanId
     * @param startTime
     * @param allowRerecord
     * @param recordedId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DeleteRecording", action = "http://mythtv.org/Dvr/DeleteRecording")
    @WebResult(name = "DeleteRecordingResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "DeleteRecording", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DeleteRecording")
    @ResponseWrapper(localName = "DeleteRecordingResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DeleteRecordingResponse")
    public Boolean deleteRecording(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "ForceDelete", targetNamespace = "http://mythtv.org")
        Boolean forceDelete,
        @WebParam(name = "AllowRerecord", targetNamespace = "http://mythtv.org")
        Boolean allowRerecord);

    /**
     * POST 
     * 
     * @param recordId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DisableRecordSchedule", action = "http://mythtv.org/Dvr/DisableRecordSchedule")
    @WebResult(name = "DisableRecordScheduleResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "DisableRecordSchedule", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DisableRecordSchedule")
    @ResponseWrapper(localName = "DisableRecordScheduleResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DisableRecordScheduleResponse")
    public Boolean disableRecordSchedule(
        @WebParam(name = "RecordId", targetNamespace = "http://mythtv.org")
        Long recordId);

    /**
     * GET 
     * 
     * @param dupIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DupInToDescription", action = "http://mythtv.org/Dvr/DupInToDescription")
    @WebResult(name = "DupInToDescriptionResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "DupInToDescription", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DupInToDescription")
    @ResponseWrapper(localName = "DupInToDescriptionResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DupInToDescriptionResponse")
    public String dupInToDescription(
        @WebParam(name = "DupIn", targetNamespace = "http://mythtv.org")
        String dupIn);

    /**
     * GET 
     * 
     * @param dupIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DupInToString", action = "http://mythtv.org/Dvr/DupInToString")
    @WebResult(name = "DupInToStringResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "DupInToString", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DupInToString")
    @ResponseWrapper(localName = "DupInToStringResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DupInToStringResponse")
    public String dupInToString(
        @WebParam(name = "DupIn", targetNamespace = "http://mythtv.org")
        String dupIn);

    /**
     * GET 
     * 
     * @param dupMethod
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DupMethodToDescription", action = "http://mythtv.org/Dvr/DupMethodToDescription")
    @WebResult(name = "DupMethodToDescriptionResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "DupMethodToDescription", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DupMethodToDescription")
    @ResponseWrapper(localName = "DupMethodToDescriptionResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DupMethodToDescriptionResponse")
    public String dupMethodToDescription(
        @WebParam(name = "DupMethod", targetNamespace = "http://mythtv.org")
        String dupMethod);

    /**
     * GET 
     * 
     * @param dupMethod
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DupMethodToString", action = "http://mythtv.org/Dvr/DupMethodToString")
    @WebResult(name = "DupMethodToStringResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "DupMethodToString", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DupMethodToString")
    @ResponseWrapper(localName = "DupMethodToStringResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.DupMethodToStringResponse")
    public String dupMethodToString(
        @WebParam(name = "DupMethod", targetNamespace = "http://mythtv.org")
        String dupMethod);

    /**
     * POST 
     * 
     * @param recordId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "EnableRecordSchedule", action = "http://mythtv.org/Dvr/EnableRecordSchedule")
    @WebResult(name = "EnableRecordScheduleResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "EnableRecordSchedule", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.EnableRecordSchedule")
    @ResponseWrapper(localName = "EnableRecordScheduleResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.EnableRecordScheduleResponse")
    public Boolean enableRecordSchedule(
        @WebParam(name = "RecordId", targetNamespace = "http://mythtv.org")
        Long recordId);

    /**
     * GET 
     * 
     * @param recordId
     * @param startIndex
     * @param count
     * @return
     *     returns mythtvapi.dvr.ProgramList
     */
    @WebMethod(operationName = "GetConflictList", action = "http://mythtv.org/Dvr/GetConflictList")
    @WebResult(name = "GetConflictListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetConflictList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetConflictList")
    @ResponseWrapper(localName = "GetConflictListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetConflictListResponse")
    public ProgramList getConflictList(
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Integer startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Integer count,
        @WebParam(name = "RecordId", targetNamespace = "http://mythtv.org")
        Integer recordId);

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.dvr.EncoderList
     */
    @WebMethod(operationName = "GetEncoderList", action = "http://mythtv.org/Dvr/GetEncoderList")
    @WebResult(name = "GetEncoderListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetEncoderList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetEncoderList")
    @ResponseWrapper(localName = "GetEncoderListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetEncoderListResponse")
    public EncoderList getEncoderList();

    /**
     * GET 
     * 
     * @param startIndex
     * @param count
     * @return
     *     returns mythtvapi.dvr.ProgramList
     */
    @WebMethod(operationName = "GetExpiringList", action = "http://mythtv.org/Dvr/GetExpiringList")
    @WebResult(name = "GetExpiringListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetExpiringList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetExpiringList")
    @ResponseWrapper(localName = "GetExpiringListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetExpiringListResponse")
    public ProgramList getExpiringList(
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Integer startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Integer count);

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.dvr.InputList
     */
    @WebMethod(operationName = "GetInputList", action = "http://mythtv.org/Dvr/GetInputList")
    @WebResult(name = "GetInputListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetInputList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetInputList")
    @ResponseWrapper(localName = "GetInputListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetInputListResponse")
    public InputList getInputList();

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.dvr.ArrayOfString
     */
    @WebMethod(operationName = "GetPlayGroupList", action = "http://mythtv.org/Dvr/GetPlayGroupList")
    @WebResult(name = "GetPlayGroupListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetPlayGroupList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetPlayGroupList")
    @ResponseWrapper(localName = "GetPlayGroupListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetPlayGroupListResponse")
    public ArrayOfString getPlayGroupList();

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.dvr.ArrayOfString
     */
    @WebMethod(operationName = "GetRecGroupList", action = "http://mythtv.org/Dvr/GetRecGroupList")
    @WebResult(name = "GetRecGroupListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecGroupList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecGroupList")
    @ResponseWrapper(localName = "GetRecGroupListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecGroupListResponse")
    public ArrayOfString getRecGroupList();

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.dvr.RecRuleFilterList
     */
    @WebMethod(operationName = "GetRecRuleFilterList", action = "http://mythtv.org/Dvr/GetRecRuleFilterList")
    @WebResult(name = "GetRecRuleFilterListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecRuleFilterList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecRuleFilterList")
    @ResponseWrapper(localName = "GetRecRuleFilterListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecRuleFilterListResponse")
    public RecRuleFilterList getRecRuleFilterList();

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.dvr.ArrayOfString
     */
    @WebMethod(operationName = "GetRecStorageGroupList", action = "http://mythtv.org/Dvr/GetRecStorageGroupList")
    @WebResult(name = "GetRecStorageGroupListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecStorageGroupList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecStorageGroupList")
    @ResponseWrapper(localName = "GetRecStorageGroupListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecStorageGroupListResponse")
    public ArrayOfString getRecStorageGroupList();

    /**
     * GET 
     * 
     * @param recordId
     * @param template
     * @param makeOverride
     * @param chanId
     * @param startTime
     * @param recordedId
     * @return
     *     returns mythtvapi.dvr.RecRule
     */
    @WebMethod(operationName = "GetRecordSchedule", action = "http://mythtv.org/Dvr/GetRecordSchedule")
    @WebResult(name = "GetRecordScheduleResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecordSchedule", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordSchedule")
    @ResponseWrapper(localName = "GetRecordScheduleResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordScheduleResponse")
    public RecRule getRecordSchedule(
        @WebParam(name = "RecordId", targetNamespace = "http://mythtv.org")
        Long recordId,
        @WebParam(name = "Template", targetNamespace = "http://mythtv.org")
        String template,
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "MakeOverride", targetNamespace = "http://mythtv.org")
        Boolean makeOverride);

    /**
     * GET 
     * 
     * @param startIndex
     * @param count
     * @param sort
     * @param descending
     * @return
     *     returns mythtvapi.dvr.RecRuleList
     */
    @WebMethod(operationName = "GetRecordScheduleList", action = "http://mythtv.org/Dvr/GetRecordScheduleList")
    @WebResult(name = "GetRecordScheduleListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecordScheduleList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordScheduleList")
    @ResponseWrapper(localName = "GetRecordScheduleListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordScheduleListResponse")
    public RecRuleList getRecordScheduleList(
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Integer startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Integer count,
        @WebParam(name = "Sort", targetNamespace = "http://mythtv.org")
        String sort,
        @WebParam(name = "Descending", targetNamespace = "http://mythtv.org")
        Boolean descending);

    /**
     * GET 
     * 
     * @param chanId
     * @param startTime
     * @param recordedId
     * @return
     *     returns mythtvapi.dvr.Program
     */
    @WebMethod(operationName = "GetRecorded", action = "http://mythtv.org/Dvr/GetRecorded")
    @WebResult(name = "GetRecordedResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecorded", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecorded")
    @ResponseWrapper(localName = "GetRecordedResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordedResponse")
    public Program getRecorded(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime);

    /**
     * GET 
     * 
     * @param offsetType
     * @param chanId
     * @param startTime
     * @param recordedId
     * @return
     *     returns mythtvapi.dvr.CutList
     */
    @WebMethod(operationName = "GetRecordedCommBreak", action = "http://mythtv.org/Dvr/GetRecordedCommBreak")
    @WebResult(name = "GetRecordedCommBreakResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecordedCommBreak", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordedCommBreak")
    @ResponseWrapper(localName = "GetRecordedCommBreakResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordedCommBreakResponse")
    public CutList getRecordedCommBreak(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "OffsetType", targetNamespace = "http://mythtv.org")
        String offsetType);

    /**
     * GET 
     * 
     * @param offsetType
     * @param chanId
     * @param startTime
     * @param recordedId
     * @return
     *     returns mythtvapi.dvr.CutList
     */
    @WebMethod(operationName = "GetRecordedCutList", action = "http://mythtv.org/Dvr/GetRecordedCutList")
    @WebResult(name = "GetRecordedCutListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecordedCutList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordedCutList")
    @ResponseWrapper(localName = "GetRecordedCutListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordedCutListResponse")
    public CutList getRecordedCutList(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "OffsetType", targetNamespace = "http://mythtv.org")
        String offsetType);

    /**
     * GET 
     * 
     * @param titleRegEx
     * @param startIndex
     * @param recGroup
     * @param count
     * @param descending
     * @param storageGroup
     * @return
     *     returns mythtvapi.dvr.ProgramList
     */
    @WebMethod(operationName = "GetRecordedList", action = "http://mythtv.org/Dvr/GetRecordedList")
    @WebResult(name = "GetRecordedListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecordedList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordedList")
    @ResponseWrapper(localName = "GetRecordedListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordedListResponse")
    public ProgramList getRecordedList(
        @WebParam(name = "Descending", targetNamespace = "http://mythtv.org")
        Boolean descending,
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Integer startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Integer count,
        @WebParam(name = "TitleRegEx", targetNamespace = "http://mythtv.org")
        String titleRegEx,
        @WebParam(name = "RecGroup", targetNamespace = "http://mythtv.org")
        String recGroup,
        @WebParam(name = "StorageGroup", targetNamespace = "http://mythtv.org")
        String storageGroup);

    /**
     * GET 
     * 
     * @param offsetType
     * @param recordedId
     * @return
     *     returns mythtvapi.dvr.CutList
     */
    @WebMethod(operationName = "GetRecordedSeek", action = "http://mythtv.org/Dvr/GetRecordedSeek")
    @WebResult(name = "GetRecordedSeekResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetRecordedSeek", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordedSeek")
    @ResponseWrapper(localName = "GetRecordedSeekResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetRecordedSeekResponse")
    public CutList getRecordedSeek(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "OffsetType", targetNamespace = "http://mythtv.org")
        String offsetType);

    /**
     * GET 
     * 
     * @param offsetType
     * @param chanId
     * @param startTime
     * @param recordedId
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "GetSavedBookmark", action = "http://mythtv.org/Dvr/GetSavedBookmark")
    @WebResult(name = "GetSavedBookmarkResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetSavedBookmark", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetSavedBookmark")
    @ResponseWrapper(localName = "GetSavedBookmarkResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetSavedBookmarkResponse")
    public Long getSavedBookmark(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "OffsetType", targetNamespace = "http://mythtv.org")
        String offsetType);

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.dvr.TitleInfoList
     */
    @WebMethod(operationName = "GetTitleInfoList", action = "http://mythtv.org/Dvr/GetTitleInfoList")
    @WebResult(name = "GetTitleInfoListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetTitleInfoList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetTitleInfoList")
    @ResponseWrapper(localName = "GetTitleInfoListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetTitleInfoListResponse")
    public TitleInfoList getTitleInfoList();

    /**
     * GET 
     * 
     * @param recGroup
     * @return
     *     returns mythtvapi.dvr.ArrayOfString
     */
    @WebMethod(operationName = "GetTitleList", action = "http://mythtv.org/Dvr/GetTitleList")
    @WebResult(name = "GetTitleListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetTitleList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetTitleList")
    @ResponseWrapper(localName = "GetTitleListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetTitleListResponse")
    public ArrayOfString getTitleList(
        @WebParam(name = "RecGroup", targetNamespace = "http://mythtv.org")
        String recGroup);

    /**
     * GET 
     * 
     * @param recordId
     * @param startIndex
     * @param showAll
     * @param count
     * @param recStatus
     * @return
     *     returns mythtvapi.dvr.ProgramList
     */
    @WebMethod(operationName = "GetUpcomingList", action = "http://mythtv.org/Dvr/GetUpcomingList")
    @WebResult(name = "GetUpcomingListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetUpcomingList", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetUpcomingList")
    @ResponseWrapper(localName = "GetUpcomingListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.GetUpcomingListResponse")
    public ProgramList getUpcomingList(
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Integer startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Integer count,
        @WebParam(name = "ShowAll", targetNamespace = "http://mythtv.org")
        Boolean showAll,
        @WebParam(name = "RecordId", targetNamespace = "http://mythtv.org")
        Integer recordId,
        @WebParam(name = "RecStatus", targetNamespace = "http://mythtv.org")
        Integer recStatus);

    /**
     * GET 
     * 
     * @param recordedId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ReactivateRecording", action = "http://mythtv.org/Dvr/ReactivateRecording")
    @WebResult(name = "ReactivateRecordingResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "ReactivateRecording", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.ReactivateRecording")
    @ResponseWrapper(localName = "ReactivateRecordingResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.ReactivateRecordingResponse")
    public Boolean reactivateRecording(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId);

    /**
     * GET 
     * 
     * @param recType
     * @param recStatus
     * @param startTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RecStatusToDescription", action = "http://mythtv.org/Dvr/RecStatusToDescription")
    @WebResult(name = "RecStatusToDescriptionResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RecStatusToDescription", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecStatusToDescription")
    @ResponseWrapper(localName = "RecStatusToDescriptionResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecStatusToDescriptionResponse")
    public String recStatusToDescription(
        @WebParam(name = "RecStatus", targetNamespace = "http://mythtv.org")
        Integer recStatus,
        @WebParam(name = "RecType", targetNamespace = "http://mythtv.org")
        Integer recType,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime);

    /**
     * GET 
     * 
     * @param recStatus
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RecStatusToString", action = "http://mythtv.org/Dvr/RecStatusToString")
    @WebResult(name = "RecStatusToStringResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RecStatusToString", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecStatusToString")
    @ResponseWrapper(localName = "RecStatusToStringResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecStatusToStringResponse")
    public String recStatusToString(
        @WebParam(name = "RecStatus", targetNamespace = "http://mythtv.org")
        Integer recStatus);

    /**
     * GET 
     * 
     * @param recType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RecTypeToDescription", action = "http://mythtv.org/Dvr/RecTypeToDescription")
    @WebResult(name = "RecTypeToDescriptionResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RecTypeToDescription", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecTypeToDescription")
    @ResponseWrapper(localName = "RecTypeToDescriptionResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecTypeToDescriptionResponse")
    public String recTypeToDescription(
        @WebParam(name = "RecType", targetNamespace = "http://mythtv.org")
        String recType);

    /**
     * GET 
     * 
     * @param recType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RecTypeToString", action = "http://mythtv.org/Dvr/RecTypeToString")
    @WebResult(name = "RecTypeToStringResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RecTypeToString", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecTypeToString")
    @ResponseWrapper(localName = "RecTypeToStringResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecTypeToStringResponse")
    public String recTypeToString(
        @WebParam(name = "RecType", targetNamespace = "http://mythtv.org")
        String recType);

    /**
     * GET 
     * 
     * @param pathname
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "RecordedIdForPathname", action = "http://mythtv.org/Dvr/RecordedIdForPathname")
    @WebResult(name = "RecordedIdForPathnameResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RecordedIdForPathname", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecordedIdForPathname")
    @ResponseWrapper(localName = "RecordedIdForPathnameResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RecordedIdForPathnameResponse")
    public Integer recordedIdForPathname(
        @WebParam(name = "Pathname", targetNamespace = "http://mythtv.org")
        String pathname);

    /**
     * POST 
     * 
     * @param recordId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveRecordSchedule", action = "http://mythtv.org/Dvr/RemoveRecordSchedule")
    @WebResult(name = "RemoveRecordScheduleResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RemoveRecordSchedule", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RemoveRecordSchedule")
    @ResponseWrapper(localName = "RemoveRecordScheduleResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RemoveRecordScheduleResponse")
    public Boolean removeRecordSchedule(
        @WebParam(name = "RecordId", targetNamespace = "http://mythtv.org")
        Long recordId);

    /**
     * POST 
     * 
     * @param forceDelete
     * @param chanId
     * @param startTime
     * @param allowRerecord
     * @param recordedId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveRecorded", action = "http://mythtv.org/Dvr/RemoveRecorded")
    @WebResult(name = "RemoveRecordedResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RemoveRecorded", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RemoveRecorded")
    @ResponseWrapper(localName = "RemoveRecordedResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RemoveRecordedResponse")
    public Boolean removeRecorded(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "ForceDelete", targetNamespace = "http://mythtv.org")
        Boolean forceDelete,
        @WebParam(name = "AllowRerecord", targetNamespace = "http://mythtv.org")
        Boolean allowRerecord);

    /**
     * GET 
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RescheduleRecordings", action = "http://mythtv.org/Dvr/RescheduleRecordings")
    @WebResult(name = "RescheduleRecordingsResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RescheduleRecordings", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RescheduleRecordings")
    @ResponseWrapper(localName = "RescheduleRecordingsResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.RescheduleRecordingsResponse")
    public Boolean rescheduleRecordings();

    /**
     * POST 
     * 
     * @param offset
     * @param offsetType
     * @param chanId
     * @param startTime
     * @param recordedId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetSavedBookmark", action = "http://mythtv.org/Dvr/SetSavedBookmark")
    @WebResult(name = "SetSavedBookmarkResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "SetSavedBookmark", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.SetSavedBookmark")
    @ResponseWrapper(localName = "SetSavedBookmarkResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.SetSavedBookmarkResponse")
    public Boolean setSavedBookmark(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "OffsetType", targetNamespace = "http://mythtv.org")
        String offsetType,
        @WebParam(name = "Offset", targetNamespace = "http://mythtv.org")
        Long offset);

    /**
     * GET 
     * 
     * @param recordedId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "StopRecording", action = "http://mythtv.org/Dvr/StopRecording")
    @WebResult(name = "StopRecordingResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "StopRecording", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.StopRecording")
    @ResponseWrapper(localName = "StopRecordingResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.StopRecordingResponse")
    public Boolean stopRecording(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId);

    /**
     * GET 
     * 
     * @param chanId
     * @param startTime
     * @param recordedId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UnDeleteRecording", action = "http://mythtv.org/Dvr/UnDeleteRecording")
    @WebResult(name = "UnDeleteRecordingResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "UnDeleteRecording", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.UnDeleteRecording")
    @ResponseWrapper(localName = "UnDeleteRecordingResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.UnDeleteRecordingResponse")
    public Boolean unDeleteRecording(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime);

    /**
     * POST 
     * 
     * @param autoMetaLookup
     * @param endOffset
     * @param findDay
     * @param description
     * @param dupMethod
     * @param episode
     * @param preferredInput
     * @param title
     * @param type
     * @param seriesId
     * @param recordId
     * @param inactive
     * @param inetref
     * @param station
     * @param autoTranscode
     * @param season
     * @param transcoder
     * @param startTime
     * @param chanId
     * @param findTime
     * @param searchType
     * @param recGroup
     * @param autoExpire
     * @param maxNewest
     * @param autoUserJob3
     * @param autoUserJob4
     * @param storageGroup
     * @param playGroup
     * @param filter
     * @param autoUserJob1
     * @param startOffset
     * @param autoUserJob2
     * @param maxEpisodes
     * @param recProfile
     * @param subtitle
     * @param endTime
     * @param category
     * @param dupIn
     * @param autoCommflag
     * @param programId
     * @param recPriority
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateRecordSchedule", action = "http://mythtv.org/Dvr/UpdateRecordSchedule")
    @WebResult(name = "UpdateRecordScheduleResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "UpdateRecordSchedule", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.UpdateRecordSchedule")
    @ResponseWrapper(localName = "UpdateRecordScheduleResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.UpdateRecordScheduleResponse")
    public Boolean updateRecordSchedule(
        @WebParam(name = "RecordId", targetNamespace = "http://mythtv.org")
        Long recordId,
        @WebParam(name = "Title", targetNamespace = "http://mythtv.org")
        String title,
        @WebParam(name = "Subtitle", targetNamespace = "http://mythtv.org")
        String subtitle,
        @WebParam(name = "Description", targetNamespace = "http://mythtv.org")
        String description,
        @WebParam(name = "Category", targetNamespace = "http://mythtv.org")
        String category,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar endTime,
        @WebParam(name = "SeriesId", targetNamespace = "http://mythtv.org")
        String seriesId,
        @WebParam(name = "ProgramId", targetNamespace = "http://mythtv.org")
        String programId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "Station", targetNamespace = "http://mythtv.org")
        String station,
        @WebParam(name = "FindDay", targetNamespace = "http://mythtv.org")
        Integer findDay,
        @WebParam(name = "FindTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar findTime,
        @WebParam(name = "Inactive", targetNamespace = "http://mythtv.org")
        Boolean inactive,
        @WebParam(name = "Season", targetNamespace = "http://mythtv.org")
        Long season,
        @WebParam(name = "Episode", targetNamespace = "http://mythtv.org")
        Long episode,
        @WebParam(name = "Inetref", targetNamespace = "http://mythtv.org")
        String inetref,
        @WebParam(name = "Type", targetNamespace = "http://mythtv.org")
        String type,
        @WebParam(name = "SearchType", targetNamespace = "http://mythtv.org")
        String searchType,
        @WebParam(name = "RecPriority", targetNamespace = "http://mythtv.org")
        Integer recPriority,
        @WebParam(name = "PreferredInput", targetNamespace = "http://mythtv.org")
        Long preferredInput,
        @WebParam(name = "StartOffset", targetNamespace = "http://mythtv.org")
        Integer startOffset,
        @WebParam(name = "EndOffset", targetNamespace = "http://mythtv.org")
        Integer endOffset,
        @WebParam(name = "DupMethod", targetNamespace = "http://mythtv.org")
        String dupMethod,
        @WebParam(name = "DupIn", targetNamespace = "http://mythtv.org")
        String dupIn,
        @WebParam(name = "Filter", targetNamespace = "http://mythtv.org")
        Long filter,
        @WebParam(name = "RecProfile", targetNamespace = "http://mythtv.org")
        String recProfile,
        @WebParam(name = "RecGroup", targetNamespace = "http://mythtv.org")
        String recGroup,
        @WebParam(name = "StorageGroup", targetNamespace = "http://mythtv.org")
        String storageGroup,
        @WebParam(name = "PlayGroup", targetNamespace = "http://mythtv.org")
        String playGroup,
        @WebParam(name = "AutoExpire", targetNamespace = "http://mythtv.org")
        Boolean autoExpire,
        @WebParam(name = "MaxEpisodes", targetNamespace = "http://mythtv.org")
        Integer maxEpisodes,
        @WebParam(name = "MaxNewest", targetNamespace = "http://mythtv.org")
        Boolean maxNewest,
        @WebParam(name = "AutoCommflag", targetNamespace = "http://mythtv.org")
        Boolean autoCommflag,
        @WebParam(name = "AutoTranscode", targetNamespace = "http://mythtv.org")
        Boolean autoTranscode,
        @WebParam(name = "AutoMetaLookup", targetNamespace = "http://mythtv.org")
        Boolean autoMetaLookup,
        @WebParam(name = "AutoUserJob1", targetNamespace = "http://mythtv.org")
        Boolean autoUserJob1,
        @WebParam(name = "AutoUserJob2", targetNamespace = "http://mythtv.org")
        Boolean autoUserJob2,
        @WebParam(name = "AutoUserJob3", targetNamespace = "http://mythtv.org")
        Boolean autoUserJob3,
        @WebParam(name = "AutoUserJob4", targetNamespace = "http://mythtv.org")
        Boolean autoUserJob4,
        @WebParam(name = "Transcoder", targetNamespace = "http://mythtv.org")
        Integer transcoder);

    /**
     * POST 
     * 
     * @param watched
     * @param chanId
     * @param startTime
     * @param recordedId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateRecordedWatchedStatus", action = "http://mythtv.org/Dvr/UpdateRecordedWatchedStatus")
    @WebResult(name = "UpdateRecordedWatchedStatusResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "UpdateRecordedWatchedStatus", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.UpdateRecordedWatchedStatus")
    @ResponseWrapper(localName = "UpdateRecordedWatchedStatusResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.dvr.UpdateRecordedWatchedStatusResponse")
    public Boolean updateRecordedWatchedStatus(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "Watched", targetNamespace = "http://mythtv.org")
        Boolean watched);

}
