
package mythtvapi.dvr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Interface Version 6.3 - 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DvrServices", targetNamespace = "http://mythtv.org", wsdlLocation = "file:/tmp/mythtv/wsdl")
public class DvrServices
    extends Service
{

    private final static URL DVRSERVICES_WSDL_LOCATION;
    private final static WebServiceException DVRSERVICES_EXCEPTION;
    private final static QName DVRSERVICES_QNAME = new QName("http://mythtv.org", "DvrServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/tmp/mythtv/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DVRSERVICES_WSDL_LOCATION = url;
        DVRSERVICES_EXCEPTION = e;
    }

    public DvrServices() {
        super(__getWsdlLocation(), DVRSERVICES_QNAME);
    }

    public DvrServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), DVRSERVICES_QNAME, features);
    }

    public DvrServices(URL wsdlLocation) {
        super(wsdlLocation, DVRSERVICES_QNAME);
    }

    public DvrServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DVRSERVICES_QNAME, features);
    }

    public DvrServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DvrServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Dvr
     */
    @WebEndpoint(name = "BasicHttpBinding_Dvr")
    public Dvr getBasicHttpBindingDvr() {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Dvr"), Dvr.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Dvr
     */
    @WebEndpoint(name = "BasicHttpBinding_Dvr")
    public Dvr getBasicHttpBindingDvr(WebServiceFeature... features) {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Dvr"), Dvr.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DVRSERVICES_EXCEPTION!= null) {
            throw DVRSERVICES_EXCEPTION;
        }
        return DVRSERVICES_WSDL_LOCATION;
    }

}
