
package mythtvapi.video;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Interface Version 1.3 - 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VideoServices", targetNamespace = "http://mythtv.org", wsdlLocation = "http://192.168.1.8:6544/Video/wsdl")
public class VideoServices
    extends Service
{

    private final static URL VIDEOSERVICES_WSDL_LOCATION;
    private final static WebServiceException VIDEOSERVICES_EXCEPTION;
    private final static QName VIDEOSERVICES_QNAME = new QName("http://mythtv.org", "VideoServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.8:6544/Video/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIDEOSERVICES_WSDL_LOCATION = url;
        VIDEOSERVICES_EXCEPTION = e;
    }

    public VideoServices() {
        super(__getWsdlLocation(), VIDEOSERVICES_QNAME);
    }

    public VideoServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIDEOSERVICES_QNAME, features);
    }

    public VideoServices(URL wsdlLocation) {
        super(wsdlLocation, VIDEOSERVICES_QNAME);
    }

    public VideoServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIDEOSERVICES_QNAME, features);
    }

    public VideoServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VideoServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Video
     */
    @WebEndpoint(name = "BasicHttpBinding_Video")
    public Video getBasicHttpBindingVideo() {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Video"), Video.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Video
     */
    @WebEndpoint(name = "BasicHttpBinding_Video")
    public Video getBasicHttpBindingVideo(WebServiceFeature... features) {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Video"), Video.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIDEOSERVICES_EXCEPTION!= null) {
            throw VIDEOSERVICES_EXCEPTION;
        }
        return VIDEOSERVICES_WSDL_LOCATION;
    }

}
