
package mythtvapi.video;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Video", targetNamespace = "http://mythtv.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Video {


    /**
     * POST 
     * 
     * @param hostName
     * @param fileName
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddVideo", action = "http://mythtv.org/Video/AddVideo")
    @WebResult(name = "AddVideoResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "AddVideo", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.AddVideo")
    @ResponseWrapper(localName = "AddVideoResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.AddVideoResponse")
    public Boolean addVideo(
        @WebParam(name = "FileName", targetNamespace = "http://mythtv.org")
        String fileName,
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName);

    /**
     * GET 
     * 
     * @param path
     * @return
     *     returns mythtvapi.video.BlurayInfo
     */
    @WebMethod(operationName = "GetBluray", action = "http://mythtv.org/Video/GetBluray")
    @WebResult(name = "GetBlurayResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetBluray", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.GetBluray")
    @ResponseWrapper(localName = "GetBlurayResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.GetBlurayResponse")
    public BlurayInfo getBluray(
        @WebParam(name = "Path", targetNamespace = "http://mythtv.org")
        String path);

    /**
     * GET 
     * 
     * @param id
     * @return
     *     returns mythtvapi.video.VideoMetadataInfo
     */
    @WebMethod(operationName = "GetVideo", action = "http://mythtv.org/Video/GetVideo")
    @WebResult(name = "GetVideoResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetVideo", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.GetVideo")
    @ResponseWrapper(localName = "GetVideoResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.GetVideoResponse")
    public VideoMetadataInfo getVideo(
        @WebParam(name = "Id", targetNamespace = "http://mythtv.org")
        Integer id);

    /**
     * GET 
     * 
     * @param fileName
     * @return
     *     returns mythtvapi.video.VideoMetadataInfo
     */
    @WebMethod(operationName = "GetVideoByFileName", action = "http://mythtv.org/Video/GetVideoByFileName")
    @WebResult(name = "GetVideoByFileNameResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetVideoByFileName", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.GetVideoByFileName")
    @ResponseWrapper(localName = "GetVideoByFileNameResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.GetVideoByFileNameResponse")
    public VideoMetadataInfo getVideoByFileName(
        @WebParam(name = "FileName", targetNamespace = "http://mythtv.org")
        String fileName);

    /**
     * GET 
     * 
     * @param startIndex
     * @param folder
     * @param count
     * @param sort
     * @param descending
     * @return
     *     returns mythtvapi.video.VideoMetadataInfoList
     */
    @WebMethod(operationName = "GetVideoList", action = "http://mythtv.org/Video/GetVideoList")
    @WebResult(name = "GetVideoListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetVideoList", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.GetVideoList")
    @ResponseWrapper(localName = "GetVideoListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.GetVideoListResponse")
    public VideoMetadataInfoList getVideoList(
        @WebParam(name = "Folder", targetNamespace = "http://mythtv.org")
        String folder,
        @WebParam(name = "Sort", targetNamespace = "http://mythtv.org")
        String sort,
        @WebParam(name = "Descending", targetNamespace = "http://mythtv.org")
        Boolean descending,
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Integer startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Integer count);

    /**
     * GET 
     * 
     * @param inetref
     * @param subtitle
     * @param season
     * @param grabberType
     * @param episode
     * @param title
     * @param allowGeneric
     * @return
     *     returns mythtvapi.video.VideoLookupList
     */
    @WebMethod(operationName = "LookupVideo", action = "http://mythtv.org/Video/LookupVideo")
    @WebResult(name = "LookupVideoResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "LookupVideo", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.LookupVideo")
    @ResponseWrapper(localName = "LookupVideoResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.LookupVideoResponse")
    public VideoLookupList lookupVideo(
        @WebParam(name = "Title", targetNamespace = "http://mythtv.org")
        String title,
        @WebParam(name = "Subtitle", targetNamespace = "http://mythtv.org")
        String subtitle,
        @WebParam(name = "Inetref", targetNamespace = "http://mythtv.org")
        String inetref,
        @WebParam(name = "Season", targetNamespace = "http://mythtv.org")
        Integer season,
        @WebParam(name = "Episode", targetNamespace = "http://mythtv.org")
        Integer episode,
        @WebParam(name = "GrabberType", targetNamespace = "http://mythtv.org")
        String grabberType,
        @WebParam(name = "AllowGeneric", targetNamespace = "http://mythtv.org")
        Boolean allowGeneric);

    /**
     * POST 
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveVideoFromDB", action = "http://mythtv.org/Video/RemoveVideoFromDB")
    @WebResult(name = "RemoveVideoFromDBResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RemoveVideoFromDB", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.RemoveVideoFromDB")
    @ResponseWrapper(localName = "RemoveVideoFromDBResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.RemoveVideoFromDBResponse")
    public Boolean removeVideoFromDB(
        @WebParam(name = "Id", targetNamespace = "http://mythtv.org")
        Integer id);

    /**
     * POST 
     * 
     * @param watched
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateVideoWatchedStatus", action = "http://mythtv.org/Video/UpdateVideoWatchedStatus")
    @WebResult(name = "UpdateVideoWatchedStatusResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "UpdateVideoWatchedStatus", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.UpdateVideoWatchedStatus")
    @ResponseWrapper(localName = "UpdateVideoWatchedStatusResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.video.UpdateVideoWatchedStatusResponse")
    public Boolean updateVideoWatchedStatus(
        @WebParam(name = "Id", targetNamespace = "http://mythtv.org")
        Integer id,
        @WebParam(name = "Watched", targetNamespace = "http://mythtv.org")
        Boolean watched);

}
