
package mythtvapi.myth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Myth", targetNamespace = "http://mythtv.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Myth {


    /**
     * POST 
     * 
     * @param hostName
     * @param groupName
     * @param dirName
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddStorageGroupDir", action = "http://mythtv.org/Myth/AddStorageGroupDir")
    @WebResult(name = "AddStorageGroupDirResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "AddStorageGroupDir", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.AddStorageGroupDir")
    @ResponseWrapper(localName = "AddStorageGroupDirResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.AddStorageGroupDirResponse")
    public Boolean addStorageGroupDir(
        @WebParam(name = "GroupName", targetNamespace = "http://mythtv.org")
        String groupName,
        @WebParam(name = "DirName", targetNamespace = "http://mythtv.org")
        String dirName,
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName);

    /**
     * POST 
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "BackupDatabase", action = "http://mythtv.org/Myth/BackupDatabase")
    @WebResult(name = "BackupDatabaseResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "BackupDatabase", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.BackupDatabase")
    @ResponseWrapper(localName = "BackupDatabaseResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.BackupDatabaseResponse")
    public Boolean backupDatabase();

    /**
     * POST 
     * 
     * @param oldPassword
     * @param newPassword
     * @param userName
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ChangePassword", action = "http://mythtv.org/Myth/ChangePassword")
    @WebResult(name = "ChangePasswordResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "ChangePassword", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ChangePassword")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ChangePasswordResponse")
    public Boolean changePassword(
        @WebParam(name = "UserName", targetNamespace = "http://mythtv.org")
        String userName,
        @WebParam(name = "OldPassword", targetNamespace = "http://mythtv.org")
        String oldPassword,
        @WebParam(name = "NewPassword", targetNamespace = "http://mythtv.org")
        String newPassword);

    /**
     * POST 
     * 
     * @param repair
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CheckDatabase", action = "http://mythtv.org/Myth/CheckDatabase")
    @WebResult(name = "CheckDatabaseResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "CheckDatabase", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.CheckDatabase")
    @ResponseWrapper(localName = "CheckDatabaseResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.CheckDatabaseResponse")
    public Boolean checkDatabase(
        @WebParam(name = "Repair", targetNamespace = "http://mythtv.org")
        Boolean repair);

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.myth.BackendInfo
     */
    @WebMethod(operationName = "GetBackendInfo", action = "http://mythtv.org/Myth/GetBackendInfo")
    @WebResult(name = "GetBackendInfoResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetBackendInfo", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetBackendInfo")
    @ResponseWrapper(localName = "GetBackendInfoResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetBackendInfoResponse")
    public BackendInfo getBackendInfo();

    /**
     * GET 
     * 
     * @param pin
     * @return
     *     returns mythtvapi.myth.ConnectionInfo
     */
    @WebMethod(operationName = "GetConnectionInfo", action = "http://mythtv.org/Myth/GetConnectionInfo")
    @WebResult(name = "GetConnectionInfoResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetConnectionInfo", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetConnectionInfo")
    @ResponseWrapper(localName = "GetConnectionInfoResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetConnectionInfoResponse")
    public ConnectionInfo getConnectionInfo(
        @WebParam(name = "Pin", targetNamespace = "http://mythtv.org")
        String pin);

    /**
     * GET 
     * 
     * @param date
     * @param shortDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFormatDate", action = "http://mythtv.org/Myth/GetFormatDate")
    @WebResult(name = "GetFormatDateResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetFormatDate", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetFormatDate")
    @ResponseWrapper(localName = "GetFormatDateResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetFormatDateResponse")
    public String getFormatDate(
        @WebParam(name = "Date", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar date,
        @WebParam(name = "ShortDate", targetNamespace = "http://mythtv.org")
        Boolean shortDate);

    /**
     * GET 
     * 
     * @param dateTime
     * @param shortDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFormatDateTime", action = "http://mythtv.org/Myth/GetFormatDateTime")
    @WebResult(name = "GetFormatDateTimeResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetFormatDateTime", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetFormatDateTime")
    @ResponseWrapper(localName = "GetFormatDateTimeResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetFormatDateTimeResponse")
    public String getFormatDateTime(
        @WebParam(name = "DateTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar dateTime,
        @WebParam(name = "ShortDate", targetNamespace = "http://mythtv.org")
        Boolean shortDate);

    /**
     * GET 
     * 
     * @param time
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFormatTime", action = "http://mythtv.org/Myth/GetFormatTime")
    @WebResult(name = "GetFormatTimeResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetFormatTime", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetFormatTime")
    @ResponseWrapper(localName = "GetFormatTimeResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetFormatTimeResponse")
    public String getFormatTime(
        @WebParam(name = "Time", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar time);

    /**
     * GET 
     * 
     * @param onLine
     * @return
     *     returns mythtvapi.myth.FrontendList
     */
    @WebMethod(operationName = "GetFrontends", action = "http://mythtv.org/Myth/GetFrontends")
    @WebResult(name = "GetFrontendsResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetFrontends", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetFrontends")
    @ResponseWrapper(localName = "GetFrontendsResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetFrontendsResponse")
    public FrontendList getFrontends(
        @WebParam(name = "OnLine", targetNamespace = "http://mythtv.org")
        Boolean onLine);

    /**
     * GET 
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetHostName", action = "http://mythtv.org/Myth/GetHostName")
    @WebResult(name = "GetHostNameResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetHostName", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetHostName")
    @ResponseWrapper(localName = "GetHostNameResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetHostNameResponse")
    public String getHostName();

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.myth.ArrayOfString
     */
    @WebMethod(operationName = "GetHosts", action = "http://mythtv.org/Myth/GetHosts")
    @WebResult(name = "GetHostsResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetHosts", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetHosts")
    @ResponseWrapper(localName = "GetHostsResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetHostsResponse")
    public ArrayOfString getHosts();

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.myth.ArrayOfString
     */
    @WebMethod(operationName = "GetKeys", action = "http://mythtv.org/Myth/GetKeys")
    @WebResult(name = "GetKeysResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetKeys", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetKeys")
    @ResponseWrapper(localName = "GetKeysResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetKeysResponse")
    public ArrayOfString getKeys();

    /**
     * GET 
     * 
     * @param hostName
     * @param filename
     * @param application
     * @param level
     * @param line
     * @param function
     * @param fromTime
     * @param pid
     * @param thread
     * @param tid
     * @param toTime
     * @param msgContains
     * @return
     *     returns mythtvapi.myth.LogMessageList
     */
    @WebMethod(operationName = "GetLogs", action = "http://mythtv.org/Myth/GetLogs")
    @WebResult(name = "GetLogsResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetLogs", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetLogs")
    @ResponseWrapper(localName = "GetLogsResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetLogsResponse")
    public LogMessageList getLogs(
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName,
        @WebParam(name = "Application", targetNamespace = "http://mythtv.org")
        String application,
        @WebParam(name = "PID", targetNamespace = "http://mythtv.org")
        Integer pid,
        @WebParam(name = "TID", targetNamespace = "http://mythtv.org")
        Integer tid,
        @WebParam(name = "Thread", targetNamespace = "http://mythtv.org")
        String thread,
        @WebParam(name = "Filename", targetNamespace = "http://mythtv.org")
        String filename,
        @WebParam(name = "Line", targetNamespace = "http://mythtv.org")
        Integer line,
        @WebParam(name = "Function", targetNamespace = "http://mythtv.org")
        String function,
        @WebParam(name = "FromTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar fromTime,
        @WebParam(name = "ToTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar toTime,
        @WebParam(name = "Level", targetNamespace = "http://mythtv.org")
        String level,
        @WebParam(name = "MsgContains", targetNamespace = "http://mythtv.org")
        String msgContains);

    /**
     * GET 
     * 
     * @param hostName
     * @param _default
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSetting", action = "http://mythtv.org/Myth/GetSetting")
    @WebResult(name = "GetSettingResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetSetting", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetSetting")
    @ResponseWrapper(localName = "GetSettingResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetSettingResponse")
    public String getSetting(
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName,
        @WebParam(name = "Key", targetNamespace = "http://mythtv.org")
        String key,
        @WebParam(name = "Default", targetNamespace = "http://mythtv.org")
        String _default);

    /**
     * GET 
     * 
     * @param hostName
     * @return
     *     returns mythtvapi.myth.SettingList
     */
    @WebMethod(operationName = "GetSettingList", action = "http://mythtv.org/Myth/GetSettingList")
    @WebResult(name = "GetSettingListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetSettingList", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetSettingList")
    @ResponseWrapper(localName = "GetSettingListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetSettingListResponse")
    public SettingList getSettingList(
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName);

    /**
     * GET 
     * 
     * @param hostName
     * @param groupName
     * @return
     *     returns mythtvapi.myth.StorageGroupDirList
     */
    @WebMethod(operationName = "GetStorageGroupDirs", action = "http://mythtv.org/Myth/GetStorageGroupDirs")
    @WebResult(name = "GetStorageGroupDirsResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetStorageGroupDirs", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetStorageGroupDirs")
    @ResponseWrapper(localName = "GetStorageGroupDirsResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetStorageGroupDirsResponse")
    public StorageGroupDirList getStorageGroupDirs(
        @WebParam(name = "GroupName", targetNamespace = "http://mythtv.org")
        String groupName,
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName);

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.myth.TimeZoneInfo
     */
    @WebMethod(operationName = "GetTimeZone", action = "http://mythtv.org/Myth/GetTimeZone")
    @WebResult(name = "GetTimeZoneResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetTimeZone", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetTimeZone")
    @ResponseWrapper(localName = "GetTimeZoneResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.GetTimeZoneResponse")
    public TimeZoneInfo getTimeZone();

    /**
     * GET 
     * 
     * @param dateTime
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "ParseISODateString", action = "http://mythtv.org/Myth/ParseISODateString")
    @WebResult(name = "ParseISODateStringResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "ParseISODateString", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ParseISODateString")
    @ResponseWrapper(localName = "ParseISODateStringResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ParseISODateStringResponse")
    public XMLGregorianCalendar parseISODateString(
        @WebParam(name = "DateTime", targetNamespace = "http://mythtv.org")
        String dateTime);

    /**
     * POST 
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ProfileDelete", action = "http://mythtv.org/Myth/ProfileDelete")
    @WebResult(name = "ProfileDeleteResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "ProfileDelete", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileDelete")
    @ResponseWrapper(localName = "ProfileDeleteResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileDeleteResponse")
    public Boolean profileDelete();

    /**
     * POST 
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ProfileSubmit", action = "http://mythtv.org/Myth/ProfileSubmit")
    @WebResult(name = "ProfileSubmitResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "ProfileSubmit", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileSubmit")
    @ResponseWrapper(localName = "ProfileSubmitResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileSubmitResponse")
    public Boolean profileSubmit();

    /**
     * GET 
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProfileText", action = "http://mythtv.org/Myth/ProfileText")
    @WebResult(name = "ProfileTextResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "ProfileText", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileText")
    @ResponseWrapper(localName = "ProfileTextResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileTextResponse")
    public String profileText();

    /**
     * GET 
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProfileURL", action = "http://mythtv.org/Myth/ProfileURL")
    @WebResult(name = "ProfileURLResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "ProfileURL", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileURL")
    @ResponseWrapper(localName = "ProfileURLResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileURLResponse")
    public String profileURL();

    /**
     * GET 
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProfileUpdated", action = "http://mythtv.org/Myth/ProfileUpdated")
    @WebResult(name = "ProfileUpdatedResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "ProfileUpdated", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileUpdated")
    @ResponseWrapper(localName = "ProfileUpdatedResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.ProfileUpdatedResponse")
    public String profileUpdated();

    /**
     * POST 
     * 
     * @param hostName
     * @param value
     * @param key
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "PutSetting", action = "http://mythtv.org/Myth/PutSetting")
    @WebResult(name = "PutSettingResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "PutSetting", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.PutSetting")
    @ResponseWrapper(localName = "PutSettingResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.PutSettingResponse")
    public Boolean putSetting(
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName,
        @WebParam(name = "Key", targetNamespace = "http://mythtv.org")
        String key,
        @WebParam(name = "Value", targetNamespace = "http://mythtv.org")
        String value);

    /**
     * POST 
     * 
     * @param hostName
     * @param groupName
     * @param dirName
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveStorageGroupDir", action = "http://mythtv.org/Myth/RemoveStorageGroupDir")
    @WebResult(name = "RemoveStorageGroupDirResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RemoveStorageGroupDir", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.RemoveStorageGroupDir")
    @ResponseWrapper(localName = "RemoveStorageGroupDirResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.RemoveStorageGroupDirResponse")
    public Boolean removeStorageGroupDir(
        @WebParam(name = "GroupName", targetNamespace = "http://mythtv.org")
        String groupName,
        @WebParam(name = "DirName", targetNamespace = "http://mythtv.org")
        String dirName,
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName);

    /**
     * POST 
     * 
     * @param address
     * @param message
     * @param udpPort
     * @param timeout
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SendMessage", action = "http://mythtv.org/Myth/SendMessage")
    @WebResult(name = "SendMessageResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.SendMessageResponse")
    public Boolean sendMessage(
        @WebParam(name = "Message", targetNamespace = "http://mythtv.org")
        String message,
        @WebParam(name = "Address", targetNamespace = "http://mythtv.org")
        String address,
        @WebParam(name = "udpPort", targetNamespace = "http://mythtv.org")
        Integer udpPort,
        @WebParam(name = "Timeout", targetNamespace = "http://mythtv.org")
        Integer timeout);

    /**
     * POST 
     * 
     * @param image
     * @param address
     * @param visibility
     * @param origin
     * @param description
     * @param error
     * @param type
     * @param message
     * @param priority
     * @param udpPort
     * @param timeout
     * @param fullscreen
     * @param extra
     * @param progress
     * @param progressText
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SendNotification", action = "http://mythtv.org/Myth/SendNotification")
    @WebResult(name = "SendNotificationResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "SendNotification", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.SendNotification")
    @ResponseWrapper(localName = "SendNotificationResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.SendNotificationResponse")
    public Boolean sendNotification(
        @WebParam(name = "Error", targetNamespace = "http://mythtv.org")
        Boolean error,
        @WebParam(name = "Type", targetNamespace = "http://mythtv.org")
        String type,
        @WebParam(name = "Message", targetNamespace = "http://mythtv.org")
        String message,
        @WebParam(name = "Origin", targetNamespace = "http://mythtv.org")
        String origin,
        @WebParam(name = "Description", targetNamespace = "http://mythtv.org")
        String description,
        @WebParam(name = "Image", targetNamespace = "http://mythtv.org")
        String image,
        @WebParam(name = "Extra", targetNamespace = "http://mythtv.org")
        String extra,
        @WebParam(name = "ProgressText", targetNamespace = "http://mythtv.org")
        String progressText,
        @WebParam(name = "Progress", targetNamespace = "http://mythtv.org")
        Float progress,
        @WebParam(name = "Timeout", targetNamespace = "http://mythtv.org")
        Integer timeout,
        @WebParam(name = "Fullscreen", targetNamespace = "http://mythtv.org")
        Boolean fullscreen,
        @WebParam(name = "Visibility", targetNamespace = "http://mythtv.org")
        Long visibility,
        @WebParam(name = "Priority", targetNamespace = "http://mythtv.org")
        Long priority,
        @WebParam(name = "Address", targetNamespace = "http://mythtv.org")
        String address,
        @WebParam(name = "udpPort", targetNamespace = "http://mythtv.org")
        Integer udpPort);

    /**
     * POST 
     * 
     * @param dbPort
     * @param hostName
     * @param password
     * @param dbName
     * @param userName
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "TestDBSettings", action = "http://mythtv.org/Myth/TestDBSettings")
    @WebResult(name = "TestDBSettingsResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "TestDBSettings", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.TestDBSettings")
    @ResponseWrapper(localName = "TestDBSettingsResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.myth.TestDBSettingsResponse")
    public Boolean testDBSettings(
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName,
        @WebParam(name = "UserName", targetNamespace = "http://mythtv.org")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://mythtv.org")
        String password,
        @WebParam(name = "DBName", targetNamespace = "http://mythtv.org")
        String dbName,
        @WebParam(name = "dbPort", targetNamespace = "http://mythtv.org")
        Integer dbPort);

}
