
package mythtvapi.myth;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Interface Version 5.0 - 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MythServices", targetNamespace = "http://mythtv.org", wsdlLocation = "http://192.168.1.8:6544/Myth/wsdl")
public class MythServices
    extends Service
{

    private final static URL MYTHSERVICES_WSDL_LOCATION;
    private final static WebServiceException MYTHSERVICES_EXCEPTION;
    private final static QName MYTHSERVICES_QNAME = new QName("http://mythtv.org", "MythServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.8:6544/Myth/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYTHSERVICES_WSDL_LOCATION = url;
        MYTHSERVICES_EXCEPTION = e;
    }

    public MythServices() {
        super(__getWsdlLocation(), MYTHSERVICES_QNAME);
    }

    public MythServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYTHSERVICES_QNAME, features);
    }

    public MythServices(URL wsdlLocation) {
        super(wsdlLocation, MYTHSERVICES_QNAME);
    }

    public MythServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYTHSERVICES_QNAME, features);
    }

    public MythServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MythServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Myth
     */
    @WebEndpoint(name = "BasicHttpBinding_Myth")
    public Myth getBasicHttpBindingMyth() {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Myth"), Myth.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Myth
     */
    @WebEndpoint(name = "BasicHttpBinding_Myth")
    public Myth getBasicHttpBindingMyth(WebServiceFeature... features) {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Myth"), Myth.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYTHSERVICES_EXCEPTION!= null) {
            throw MYTHSERVICES_EXCEPTION;
        }
        return MYTHSERVICES_WSDL_LOCATION;
    }

}
