
package mythtvapi.guide;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Interface Version 2.2 - 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GuideServices", targetNamespace = "http://mythtv.org", wsdlLocation = "file:/tmp/mythtv/wsdl")
public class GuideServices
    extends Service
{

    private final static URL GUIDESERVICES_WSDL_LOCATION;
    private final static WebServiceException GUIDESERVICES_EXCEPTION;
    private final static QName GUIDESERVICES_QNAME = new QName("http://mythtv.org", "GuideServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/tmp/mythtv/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GUIDESERVICES_WSDL_LOCATION = url;
        GUIDESERVICES_EXCEPTION = e;
    }

    public GuideServices() {
        super(__getWsdlLocation(), GUIDESERVICES_QNAME);
    }

    public GuideServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), GUIDESERVICES_QNAME, features);
    }

    public GuideServices(URL wsdlLocation) {
        super(wsdlLocation, GUIDESERVICES_QNAME);
    }

    public GuideServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GUIDESERVICES_QNAME, features);
    }

    public GuideServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GuideServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Guide
     */
    @WebEndpoint(name = "BasicHttpBinding_Guide")
    public Guide getBasicHttpBindingGuide() {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Guide"), Guide.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Guide
     */
    @WebEndpoint(name = "BasicHttpBinding_Guide")
    public Guide getBasicHttpBindingGuide(WebServiceFeature... features) {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Guide"), Guide.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GUIDESERVICES_EXCEPTION!= null) {
            throw GUIDESERVICES_EXCEPTION;
        }
        return GUIDESERVICES_WSDL_LOCATION;
    }

}
