
package mythtvapi.guide;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Guide", targetNamespace = "http://mythtv.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Guide {


    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.guide.ArrayOfString
     */
    @WebMethod(operationName = "GetCategoryList", action = "http://mythtv.org/Guide/GetCategoryList")
    @WebResult(name = "GetCategoryListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetCategoryList", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetCategoryList")
    @ResponseWrapper(localName = "GetCategoryListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetCategoryListResponse")
    public ArrayOfString getCategoryList();

    /**
     * GET 
     * 
     * @param includeEmpty
     * @return
     *     returns mythtvapi.guide.ChannelGroupList
     */
    @WebMethod(operationName = "GetChannelGroupList", action = "http://mythtv.org/Guide/GetChannelGroupList")
    @WebResult(name = "GetChannelGroupListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetChannelGroupList", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetChannelGroupList")
    @ResponseWrapper(localName = "GetChannelGroupListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetChannelGroupListResponse")
    public ChannelGroupList getChannelGroupList(
        @WebParam(name = "IncludeEmpty", targetNamespace = "http://mythtv.org")
        Boolean includeEmpty);

    /**
     * GET 
     * 
     * @param width
     * @param chanId
     * @param height
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetChannelIcon", action = "http://mythtv.org/Guide/GetChannelIcon")
    @WebResult(name = "GetChannelIconResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetChannelIcon", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetChannelIcon")
    @ResponseWrapper(localName = "GetChannelIconResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetChannelIconResponse")
    public String getChannelIcon(
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "Width", targetNamespace = "http://mythtv.org")
        Integer width,
        @WebParam(name = "Height", targetNamespace = "http://mythtv.org")
        Integer height);

    /**
     * GET 
     * 
     * @param chanId
     * @param startTime
     * @return
     *     returns mythtvapi.guide.Program
     */
    @WebMethod(operationName = "GetProgramDetails", action = "http://mythtv.org/Guide/GetProgramDetails")
    @WebResult(name = "GetProgramDetailsResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetProgramDetails", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetProgramDetails")
    @ResponseWrapper(localName = "GetProgramDetailsResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetProgramDetailsResponse")
    public Program getProgramDetails(
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime);

    /**
     * GET 
     * 
     * @param channelGroupId
     * @param startIndex
     * @param count
     * @param startTime
     * @param details
     * @param endTime
     * @return
     *     returns mythtvapi.guide.ProgramGuide
     */
    @WebMethod(operationName = "GetProgramGuide", action = "http://mythtv.org/Guide/GetProgramGuide")
    @WebResult(name = "GetProgramGuideResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetProgramGuide", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetProgramGuide")
    @ResponseWrapper(localName = "GetProgramGuideResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetProgramGuideResponse")
    public ProgramGuide getProgramGuide(
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar endTime,
        @WebParam(name = "Details", targetNamespace = "http://mythtv.org")
        Boolean details,
        @WebParam(name = "ChannelGroupId", targetNamespace = "http://mythtv.org")
        Integer channelGroupId,
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Integer startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Integer count);

    /**
     * GET 
     * 
     * @param keywordFilter
     * @param onlyNew
     * @param count
     * @param sort
     * @param descending
     * @param personFilter
     * @param startIndex
     * @param titleFilter
     * @param categoryFilter
     * @param startTime
     * @param chanId
     * @param details
     * @param endTime
     * @return
     *     returns mythtvapi.guide.ProgramList
     */
    @WebMethod(operationName = "GetProgramList", action = "http://mythtv.org/Guide/GetProgramList")
    @WebResult(name = "GetProgramListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetProgramList", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetProgramList")
    @ResponseWrapper(localName = "GetProgramListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetProgramListResponse")
    public ProgramList getProgramList(
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Integer startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Integer count,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar endTime,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "TitleFilter", targetNamespace = "http://mythtv.org")
        String titleFilter,
        @WebParam(name = "CategoryFilter", targetNamespace = "http://mythtv.org")
        String categoryFilter,
        @WebParam(name = "PersonFilter", targetNamespace = "http://mythtv.org")
        String personFilter,
        @WebParam(name = "KeywordFilter", targetNamespace = "http://mythtv.org")
        String keywordFilter,
        @WebParam(name = "OnlyNew", targetNamespace = "http://mythtv.org")
        Boolean onlyNew,
        @WebParam(name = "Details", targetNamespace = "http://mythtv.org")
        Boolean details,
        @WebParam(name = "Sort", targetNamespace = "http://mythtv.org")
        String sort,
        @WebParam(name = "Descending", targetNamespace = "http://mythtv.org")
        Boolean descending);

    /**
     * GET 
     * 
     * @param type
     * @return
     *     returns mythtvapi.guide.ArrayOfString
     */
    @WebMethod(operationName = "GetStoredSearches", action = "http://mythtv.org/Guide/GetStoredSearches")
    @WebResult(name = "GetStoredSearchesResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetStoredSearches", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetStoredSearches")
    @ResponseWrapper(localName = "GetStoredSearchesResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.guide.GetStoredSearchesResponse")
    public ArrayOfString getStoredSearches(
        @WebParam(name = "Type", targetNamespace = "http://mythtv.org")
        String type);

}
