
package mythtvapi.capture;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Capture", targetNamespace = "http://mythtv.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Capture {


    /**
     * POST 
     * 
     * @param hostName
     * @param dvbOnDemand
     * @param diSEqCId
     * @param dvbWaitForSeqStart
     * @param skipBTAudio
     * @param dvbeitScan
     * @param cardType
     * @param firewireConnection
     * @param videoDevice
     * @param vbiDevice
     * @param dvbswFilter
     * @param firewireModel
     * @param colour
     * @param brightness
     * @param dvbSatType
     * @param channelTimeout
     * @param contrast
     * @param signalTimeout
     * @param hue
     * @param audioRateLimit
     * @param dvbTuningDelay
     * @param audioDevice
     * @param dvbDiSEqCType
     * @param firewireSpeed
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "AddCaptureCard", action = "http://mythtv.org/Capture/AddCaptureCard")
    @WebResult(name = "AddCaptureCardResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "AddCaptureCard", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.AddCaptureCard")
    @ResponseWrapper(localName = "AddCaptureCardResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.AddCaptureCardResponse")
    public Integer addCaptureCard(
        @WebParam(name = "VideoDevice", targetNamespace = "http://mythtv.org")
        String videoDevice,
        @WebParam(name = "AudioDevice", targetNamespace = "http://mythtv.org")
        String audioDevice,
        @WebParam(name = "VBIDevice", targetNamespace = "http://mythtv.org")
        String vbiDevice,
        @WebParam(name = "CardType", targetNamespace = "http://mythtv.org")
        String cardType,
        @WebParam(name = "AudioRateLimit", targetNamespace = "http://mythtv.org")
        Long audioRateLimit,
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName,
        @WebParam(name = "DVBSWFilter", targetNamespace = "http://mythtv.org")
        Long dvbswFilter,
        @WebParam(name = "DVBSatType", targetNamespace = "http://mythtv.org")
        Long dvbSatType,
        @WebParam(name = "DVBWaitForSeqStart", targetNamespace = "http://mythtv.org")
        Boolean dvbWaitForSeqStart,
        @WebParam(name = "SkipBTAudio", targetNamespace = "http://mythtv.org")
        Boolean skipBTAudio,
        @WebParam(name = "DVBOnDemand", targetNamespace = "http://mythtv.org")
        Boolean dvbOnDemand,
        @WebParam(name = "DVBDiSEqCType", targetNamespace = "http://mythtv.org")
        Long dvbDiSEqCType,
        @WebParam(name = "FirewireSpeed", targetNamespace = "http://mythtv.org")
        Long firewireSpeed,
        @WebParam(name = "FirewireModel", targetNamespace = "http://mythtv.org")
        String firewireModel,
        @WebParam(name = "FirewireConnection", targetNamespace = "http://mythtv.org")
        Long firewireConnection,
        @WebParam(name = "SignalTimeout", targetNamespace = "http://mythtv.org")
        Long signalTimeout,
        @WebParam(name = "ChannelTimeout", targetNamespace = "http://mythtv.org")
        Long channelTimeout,
        @WebParam(name = "DVBTuningDelay", targetNamespace = "http://mythtv.org")
        Long dvbTuningDelay,
        @WebParam(name = "Contrast", targetNamespace = "http://mythtv.org")
        Long contrast,
        @WebParam(name = "Brightness", targetNamespace = "http://mythtv.org")
        Long brightness,
        @WebParam(name = "Colour", targetNamespace = "http://mythtv.org")
        Long colour,
        @WebParam(name = "Hue", targetNamespace = "http://mythtv.org")
        Long hue,
        @WebParam(name = "DiSEqCId", targetNamespace = "http://mythtv.org")
        Long diSEqCId,
        @WebParam(name = "DVBEITScan", targetNamespace = "http://mythtv.org")
        Boolean dvbeitScan);

    /**
     * POST 
     * 
     * @param sourceId
     * @param schedOrder
     * @param hostName
     * @param displayName
     * @param dishnetEIT
     * @param inputName
     * @param externalCommand
     * @param tuneChan
     * @param quicktune
     * @param cardId
     * @param liveTVOrder
     * @param changerModel
     * @param startChan
     * @param changerDevice
     * @param recPriority
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "AddCardInput", action = "http://mythtv.org/Capture/AddCardInput")
    @WebResult(name = "AddCardInputResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "AddCardInput", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.AddCardInput")
    @ResponseWrapper(localName = "AddCardInputResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.AddCardInputResponse")
    public Integer addCardInput(
        @WebParam(name = "CardId", targetNamespace = "http://mythtv.org")
        Long cardId,
        @WebParam(name = "SourceId", targetNamespace = "http://mythtv.org")
        Long sourceId,
        @WebParam(name = "InputName", targetNamespace = "http://mythtv.org")
        String inputName,
        @WebParam(name = "ExternalCommand", targetNamespace = "http://mythtv.org")
        String externalCommand,
        @WebParam(name = "ChangerDevice", targetNamespace = "http://mythtv.org")
        String changerDevice,
        @WebParam(name = "ChangerModel", targetNamespace = "http://mythtv.org")
        String changerModel,
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName,
        @WebParam(name = "TuneChan", targetNamespace = "http://mythtv.org")
        String tuneChan,
        @WebParam(name = "StartChan", targetNamespace = "http://mythtv.org")
        String startChan,
        @WebParam(name = "DisplayName", targetNamespace = "http://mythtv.org")
        String displayName,
        @WebParam(name = "DishnetEIT", targetNamespace = "http://mythtv.org")
        Boolean dishnetEIT,
        @WebParam(name = "RecPriority", targetNamespace = "http://mythtv.org")
        Long recPriority,
        @WebParam(name = "Quicktune", targetNamespace = "http://mythtv.org")
        Long quicktune,
        @WebParam(name = "SchedOrder", targetNamespace = "http://mythtv.org")
        Long schedOrder,
        @WebParam(name = "LiveTVOrder", targetNamespace = "http://mythtv.org")
        Long liveTVOrder);

    /**
     * GET 
     * 
     * @param cardId
     * @return
     *     returns mythtvapi.capture.CaptureCard
     */
    @WebMethod(operationName = "GetCaptureCard", action = "http://mythtv.org/Capture/GetCaptureCard")
    @WebResult(name = "GetCaptureCardResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetCaptureCard", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.GetCaptureCard")
    @ResponseWrapper(localName = "GetCaptureCardResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.GetCaptureCardResponse")
    public CaptureCard getCaptureCard(
        @WebParam(name = "CardId", targetNamespace = "http://mythtv.org")
        Integer cardId);

    /**
     * GET 
     * 
     * @param hostName
     * @param cardType
     * @return
     *     returns mythtvapi.capture.CaptureCardList
     */
    @WebMethod(operationName = "GetCaptureCardList", action = "http://mythtv.org/Capture/GetCaptureCardList")
    @WebResult(name = "GetCaptureCardListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetCaptureCardList", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.GetCaptureCardList")
    @ResponseWrapper(localName = "GetCaptureCardListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.GetCaptureCardListResponse")
    public CaptureCardList getCaptureCardList(
        @WebParam(name = "HostName", targetNamespace = "http://mythtv.org")
        String hostName,
        @WebParam(name = "CardType", targetNamespace = "http://mythtv.org")
        String cardType);

    /**
     * POST 
     * 
     * @param cardId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveCaptureCard", action = "http://mythtv.org/Capture/RemoveCaptureCard")
    @WebResult(name = "RemoveCaptureCardResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RemoveCaptureCard", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.RemoveCaptureCard")
    @ResponseWrapper(localName = "RemoveCaptureCardResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.RemoveCaptureCardResponse")
    public Boolean removeCaptureCard(
        @WebParam(name = "CardId", targetNamespace = "http://mythtv.org")
        Integer cardId);

    /**
     * POST 
     * 
     * @param cardInputId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveCardInput", action = "http://mythtv.org/Capture/RemoveCardInput")
    @WebResult(name = "RemoveCardInputResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RemoveCardInput", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.RemoveCardInput")
    @ResponseWrapper(localName = "RemoveCardInputResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.RemoveCardInputResponse")
    public Boolean removeCardInput(
        @WebParam(name = "CardInputId", targetNamespace = "http://mythtv.org")
        Integer cardInputId);

    /**
     * POST 
     * 
     * @param cardId
     * @param value
     * @param setting
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateCaptureCard", action = "http://mythtv.org/Capture/UpdateCaptureCard")
    @WebResult(name = "UpdateCaptureCardResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "UpdateCaptureCard", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.UpdateCaptureCard")
    @ResponseWrapper(localName = "UpdateCaptureCardResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.UpdateCaptureCardResponse")
    public Boolean updateCaptureCard(
        @WebParam(name = "CardId", targetNamespace = "http://mythtv.org")
        Integer cardId,
        @WebParam(name = "Setting", targetNamespace = "http://mythtv.org")
        String setting,
        @WebParam(name = "Value", targetNamespace = "http://mythtv.org")
        String value);

    /**
     * POST 
     * 
     * @param cardInputId
     * @param value
     * @param setting
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateCardInput", action = "http://mythtv.org/Capture/UpdateCardInput")
    @WebResult(name = "UpdateCardInputResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "UpdateCardInput", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.UpdateCardInput")
    @ResponseWrapper(localName = "UpdateCardInputResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.capture.UpdateCardInputResponse")
    public Boolean updateCardInput(
        @WebParam(name = "CardInputId", targetNamespace = "http://mythtv.org")
        Integer cardInputId,
        @WebParam(name = "Setting", targetNamespace = "http://mythtv.org")
        String setting,
        @WebParam(name = "Value", targetNamespace = "http://mythtv.org")
        String value);

}
