
package mythtvapi.capture;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Interface Version 1.4 - 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CaptureServices", targetNamespace = "http://mythtv.org", wsdlLocation = "http://192.168.1.8:6544/Capture/wsdl")
public class CaptureServices
    extends Service
{

    private final static URL CAPTURESERVICES_WSDL_LOCATION;
    private final static WebServiceException CAPTURESERVICES_EXCEPTION;
    private final static QName CAPTURESERVICES_QNAME = new QName("http://mythtv.org", "CaptureServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.8:6544/Capture/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAPTURESERVICES_WSDL_LOCATION = url;
        CAPTURESERVICES_EXCEPTION = e;
    }

    public CaptureServices() {
        super(__getWsdlLocation(), CAPTURESERVICES_QNAME);
    }

    public CaptureServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAPTURESERVICES_QNAME, features);
    }

    public CaptureServices(URL wsdlLocation) {
        super(wsdlLocation, CAPTURESERVICES_QNAME);
    }

    public CaptureServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAPTURESERVICES_QNAME, features);
    }

    public CaptureServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaptureServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Capture
     */
    @WebEndpoint(name = "BasicHttpBinding_Capture")
    public Capture getBasicHttpBindingCapture() {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Capture"), Capture.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Capture
     */
    @WebEndpoint(name = "BasicHttpBinding_Capture")
    public Capture getBasicHttpBindingCapture(WebServiceFeature... features) {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Capture"), Capture.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAPTURESERVICES_EXCEPTION!= null) {
            throw CAPTURESERVICES_EXCEPTION;
        }
        return CAPTURESERVICES_WSDL_LOCATION;
    }

}
