
package mythtvapi.channel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Channel", targetNamespace = "http://mythtv.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Channel {


    /**
     * POST 
     * 
     * @param sourceID
     * @param xmltvid
     * @param useEIT
     * @param visible
     * @param channelNumber
     * @param icon
     * @param format
     * @param defaultAuthority
     * @param callSign
     * @param atscMinorChannel
     * @param mplexID
     * @param frequencyID
     * @param channelName
     * @param serviceID
     * @param channelID
     * @param atscMajorChannel
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddDBChannel", action = "http://mythtv.org/Channel/AddDBChannel")
    @WebResult(name = "AddDBChannelResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "AddDBChannel", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.AddDBChannel")
    @ResponseWrapper(localName = "AddDBChannelResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.AddDBChannelResponse")
    public Boolean addDBChannel(
        @WebParam(name = "MplexID", targetNamespace = "http://mythtv.org")
        Long mplexID,
        @WebParam(name = "SourceID", targetNamespace = "http://mythtv.org")
        Long sourceID,
        @WebParam(name = "ChannelID", targetNamespace = "http://mythtv.org")
        Long channelID,
        @WebParam(name = "CallSign", targetNamespace = "http://mythtv.org")
        String callSign,
        @WebParam(name = "ChannelName", targetNamespace = "http://mythtv.org")
        String channelName,
        @WebParam(name = "ChannelNumber", targetNamespace = "http://mythtv.org")
        String channelNumber,
        @WebParam(name = "ServiceID", targetNamespace = "http://mythtv.org")
        Long serviceID,
        @WebParam(name = "ATSCMajorChannel", targetNamespace = "http://mythtv.org")
        Long atscMajorChannel,
        @WebParam(name = "ATSCMinorChannel", targetNamespace = "http://mythtv.org")
        Long atscMinorChannel,
        @WebParam(name = "UseEIT", targetNamespace = "http://mythtv.org")
        Boolean useEIT,
        @WebParam(name = "Visible", targetNamespace = "http://mythtv.org")
        Boolean visible,
        @WebParam(name = "FrequencyID", targetNamespace = "http://mythtv.org")
        String frequencyID,
        @WebParam(name = "Icon", targetNamespace = "http://mythtv.org")
        String icon,
        @WebParam(name = "Format", targetNamespace = "http://mythtv.org")
        String format,
        @WebParam(name = "XMLTVID", targetNamespace = "http://mythtv.org")
        String xmltvid,
        @WebParam(name = "DefaultAuthority", targetNamespace = "http://mythtv.org")
        String defaultAuthority);

    /**
     * POST 
     * 
     * @param lineupId
     * @param password
     * @param useEIT
     * @param freqTable
     * @param configPath
     * @param sourceName
     * @param nitId
     * @param grabber
     * @param userId
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "AddVideoSource", action = "http://mythtv.org/Channel/AddVideoSource")
    @WebResult(name = "AddVideoSourceResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "AddVideoSource", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.AddVideoSource")
    @ResponseWrapper(localName = "AddVideoSourceResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.AddVideoSourceResponse")
    public Integer addVideoSource(
        @WebParam(name = "SourceName", targetNamespace = "http://mythtv.org")
        String sourceName,
        @WebParam(name = "Grabber", targetNamespace = "http://mythtv.org")
        String grabber,
        @WebParam(name = "UserId", targetNamespace = "http://mythtv.org")
        String userId,
        @WebParam(name = "FreqTable", targetNamespace = "http://mythtv.org")
        String freqTable,
        @WebParam(name = "LineupId", targetNamespace = "http://mythtv.org")
        String lineupId,
        @WebParam(name = "Password", targetNamespace = "http://mythtv.org")
        String password,
        @WebParam(name = "UseEIT", targetNamespace = "http://mythtv.org")
        Boolean useEIT,
        @WebParam(name = "ConfigPath", targetNamespace = "http://mythtv.org")
        String configPath,
        @WebParam(name = "NITId", targetNamespace = "http://mythtv.org")
        Integer nitId);

    /**
     * GET 
     * 
     * @param sourceId
     * @param cardId
     * @param waitForFinish
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "FetchChannelsFromSource", action = "http://mythtv.org/Channel/FetchChannelsFromSource")
    @WebResult(name = "FetchChannelsFromSourceResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "FetchChannelsFromSource", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.FetchChannelsFromSource")
    @ResponseWrapper(localName = "FetchChannelsFromSourceResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.FetchChannelsFromSourceResponse")
    public Integer fetchChannelsFromSource(
        @WebParam(name = "SourceId", targetNamespace = "http://mythtv.org")
        Long sourceId,
        @WebParam(name = "CardId", targetNamespace = "http://mythtv.org")
        Long cardId,
        @WebParam(name = "WaitForFinish", targetNamespace = "http://mythtv.org")
        Boolean waitForFinish);

    /**
     * GET 
     * 
     * @param chanID
     * @return
     *     returns mythtvapi.channel.ChannelInfo
     */
    @WebMethod(operationName = "GetChannelInfo", action = "http://mythtv.org/Channel/GetChannelInfo")
    @WebResult(name = "GetChannelInfoResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetChannelInfo", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetChannelInfo")
    @ResponseWrapper(localName = "GetChannelInfoResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetChannelInfoResponse")
    public ChannelInfo getChannelInfo(
        @WebParam(name = "ChanID", targetNamespace = "http://mythtv.org")
        Long chanID);

    /**
     * GET 
     * 
     * @param sourceID
     * @param startIndex
     * @param count
     * @param onlyVisible
     * @param details
     * @return
     *     returns mythtvapi.channel.ChannelInfoList
     */
    @WebMethod(operationName = "GetChannelInfoList", action = "http://mythtv.org/Channel/GetChannelInfoList")
    @WebResult(name = "GetChannelInfoListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetChannelInfoList", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetChannelInfoList")
    @ResponseWrapper(localName = "GetChannelInfoListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetChannelInfoListResponse")
    public ChannelInfoList getChannelInfoList(
        @WebParam(name = "SourceID", targetNamespace = "http://mythtv.org")
        Long sourceID,
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Long startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Long count,
        @WebParam(name = "OnlyVisible", targetNamespace = "http://mythtv.org")
        Boolean onlyVisible,
        @WebParam(name = "Details", targetNamespace = "http://mythtv.org")
        Boolean details);

    /**
     * GET 
     * 
     * @param password
     * @param source
     * @param userId
     * @return
     *     returns mythtvapi.channel.LineupList
     */
    @WebMethod(operationName = "GetDDLineupList", action = "http://mythtv.org/Channel/GetDDLineupList")
    @WebResult(name = "GetDDLineupListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetDDLineupList", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetDDLineupList")
    @ResponseWrapper(localName = "GetDDLineupListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetDDLineupListResponse")
    public LineupList getDDLineupList(
        @WebParam(name = "Source", targetNamespace = "http://mythtv.org")
        String source,
        @WebParam(name = "UserId", targetNamespace = "http://mythtv.org")
        String userId,
        @WebParam(name = "Password", targetNamespace = "http://mythtv.org")
        String password);

    /**
     * GET 
     * 
     * @param mplexID
     * @return
     *     returns mythtvapi.channel.VideoMultiplex
     */
    @WebMethod(operationName = "GetVideoMultiplex", action = "http://mythtv.org/Channel/GetVideoMultiplex")
    @WebResult(name = "GetVideoMultiplexResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetVideoMultiplex", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetVideoMultiplex")
    @ResponseWrapper(localName = "GetVideoMultiplexResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetVideoMultiplexResponse")
    public VideoMultiplex getVideoMultiplex(
        @WebParam(name = "MplexID", targetNamespace = "http://mythtv.org")
        Long mplexID);

    /**
     * GET 
     * 
     * @param sourceID
     * @param startIndex
     * @param count
     * @return
     *     returns mythtvapi.channel.VideoMultiplexList
     */
    @WebMethod(operationName = "GetVideoMultiplexList", action = "http://mythtv.org/Channel/GetVideoMultiplexList")
    @WebResult(name = "GetVideoMultiplexListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetVideoMultiplexList", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetVideoMultiplexList")
    @ResponseWrapper(localName = "GetVideoMultiplexListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetVideoMultiplexListResponse")
    public VideoMultiplexList getVideoMultiplexList(
        @WebParam(name = "SourceID", targetNamespace = "http://mythtv.org")
        Long sourceID,
        @WebParam(name = "StartIndex", targetNamespace = "http://mythtv.org")
        Long startIndex,
        @WebParam(name = "Count", targetNamespace = "http://mythtv.org")
        Long count);

    /**
     * GET 
     * 
     * @param sourceID
     * @return
     *     returns mythtvapi.channel.VideoSource
     */
    @WebMethod(operationName = "GetVideoSource", action = "http://mythtv.org/Channel/GetVideoSource")
    @WebResult(name = "GetVideoSourceResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetVideoSource", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetVideoSource")
    @ResponseWrapper(localName = "GetVideoSourceResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetVideoSourceResponse")
    public VideoSource getVideoSource(
        @WebParam(name = "SourceID", targetNamespace = "http://mythtv.org")
        Long sourceID);

    /**
     * GET 
     * 
     * @return
     *     returns mythtvapi.channel.VideoSourceList
     */
    @WebMethod(operationName = "GetVideoSourceList", action = "http://mythtv.org/Channel/GetVideoSourceList")
    @WebResult(name = "GetVideoSourceListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetVideoSourceList", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetVideoSourceList")
    @ResponseWrapper(localName = "GetVideoSourceListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetVideoSourceListResponse")
    public VideoSourceList getVideoSourceList();

    /**
     * GET 
     * 
     * @param sourceID
     * @return
     *     returns mythtvapi.channel.ArrayOfString
     */
    @WebMethod(operationName = "GetXMLTVIdList", action = "http://mythtv.org/Channel/GetXMLTVIdList")
    @WebResult(name = "GetXMLTVIdListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetXMLTVIdList", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetXMLTVIdList")
    @ResponseWrapper(localName = "GetXMLTVIdListResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.GetXMLTVIdListResponse")
    public ArrayOfString getXMLTVIdList(
        @WebParam(name = "SourceID", targetNamespace = "http://mythtv.org")
        Long sourceID);

    /**
     * POST 
     * 
     * @param channelID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveDBChannel", action = "http://mythtv.org/Channel/RemoveDBChannel")
    @WebResult(name = "RemoveDBChannelResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RemoveDBChannel", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.RemoveDBChannel")
    @ResponseWrapper(localName = "RemoveDBChannelResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.RemoveDBChannelResponse")
    public Boolean removeDBChannel(
        @WebParam(name = "ChannelID", targetNamespace = "http://mythtv.org")
        Long channelID);

    /**
     * POST 
     * 
     * @param sourceID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RemoveVideoSource", action = "http://mythtv.org/Channel/RemoveVideoSource")
    @WebResult(name = "RemoveVideoSourceResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "RemoveVideoSource", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.RemoveVideoSource")
    @ResponseWrapper(localName = "RemoveVideoSourceResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.RemoveVideoSourceResponse")
    public Boolean removeVideoSource(
        @WebParam(name = "SourceID", targetNamespace = "http://mythtv.org")
        Long sourceID);

    /**
     * POST 
     * 
     * @param sourceID
     * @param xmltvid
     * @param useEIT
     * @param visible
     * @param channelNumber
     * @param icon
     * @param format
     * @param defaultAuthority
     * @param callSign
     * @param atscMinorChannel
     * @param mplexID
     * @param frequencyID
     * @param channelName
     * @param serviceID
     * @param channelID
     * @param atscMajorChannel
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateDBChannel", action = "http://mythtv.org/Channel/UpdateDBChannel")
    @WebResult(name = "UpdateDBChannelResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "UpdateDBChannel", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.UpdateDBChannel")
    @ResponseWrapper(localName = "UpdateDBChannelResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.UpdateDBChannelResponse")
    public Boolean updateDBChannel(
        @WebParam(name = "MplexID", targetNamespace = "http://mythtv.org")
        Long mplexID,
        @WebParam(name = "SourceID", targetNamespace = "http://mythtv.org")
        Long sourceID,
        @WebParam(name = "ChannelID", targetNamespace = "http://mythtv.org")
        Long channelID,
        @WebParam(name = "CallSign", targetNamespace = "http://mythtv.org")
        String callSign,
        @WebParam(name = "ChannelName", targetNamespace = "http://mythtv.org")
        String channelName,
        @WebParam(name = "ChannelNumber", targetNamespace = "http://mythtv.org")
        String channelNumber,
        @WebParam(name = "ServiceID", targetNamespace = "http://mythtv.org")
        Long serviceID,
        @WebParam(name = "ATSCMajorChannel", targetNamespace = "http://mythtv.org")
        Long atscMajorChannel,
        @WebParam(name = "ATSCMinorChannel", targetNamespace = "http://mythtv.org")
        Long atscMinorChannel,
        @WebParam(name = "UseEIT", targetNamespace = "http://mythtv.org")
        Boolean useEIT,
        @WebParam(name = "Visible", targetNamespace = "http://mythtv.org")
        Boolean visible,
        @WebParam(name = "FrequencyID", targetNamespace = "http://mythtv.org")
        String frequencyID,
        @WebParam(name = "Icon", targetNamespace = "http://mythtv.org")
        String icon,
        @WebParam(name = "Format", targetNamespace = "http://mythtv.org")
        String format,
        @WebParam(name = "XMLTVID", targetNamespace = "http://mythtv.org")
        String xmltvid,
        @WebParam(name = "DefaultAuthority", targetNamespace = "http://mythtv.org")
        String defaultAuthority);

    /**
     * POST 
     * 
     * @param sourceID
     * @param lineupId
     * @param password
     * @param useEIT
     * @param freqTable
     * @param configPath
     * @param sourceName
     * @param nitId
     * @param grabber
     * @param userId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateVideoSource", action = "http://mythtv.org/Channel/UpdateVideoSource")
    @WebResult(name = "UpdateVideoSourceResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "UpdateVideoSource", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.UpdateVideoSource")
    @ResponseWrapper(localName = "UpdateVideoSourceResponse", targetNamespace = "http://mythtv.org", className = "mythtvapi.channel.UpdateVideoSourceResponse")
    public Boolean updateVideoSource(
        @WebParam(name = "SourceID", targetNamespace = "http://mythtv.org")
        Long sourceID,
        @WebParam(name = "SourceName", targetNamespace = "http://mythtv.org")
        String sourceName,
        @WebParam(name = "Grabber", targetNamespace = "http://mythtv.org")
        String grabber,
        @WebParam(name = "UserId", targetNamespace = "http://mythtv.org")
        String userId,
        @WebParam(name = "FreqTable", targetNamespace = "http://mythtv.org")
        String freqTable,
        @WebParam(name = "LineupId", targetNamespace = "http://mythtv.org")
        String lineupId,
        @WebParam(name = "Password", targetNamespace = "http://mythtv.org")
        String password,
        @WebParam(name = "UseEIT", targetNamespace = "http://mythtv.org")
        Boolean useEIT,
        @WebParam(name = "ConfigPath", targetNamespace = "http://mythtv.org")
        String configPath,
        @WebParam(name = "NITId", targetNamespace = "http://mythtv.org")
        Integer nitId);

}
