
package mythtvapi.content;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Interface Version 2.0 - 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContentServices", targetNamespace = "http://mythtv.org", wsdlLocation = "http://192.168.1.8:6544/Content/wsdl")
public class ContentServices
    extends Service
{

    private final static URL CONTENTSERVICES_WSDL_LOCATION;
    private final static WebServiceException CONTENTSERVICES_EXCEPTION;
    private final static QName CONTENTSERVICES_QNAME = new QName("http://mythtv.org", "ContentServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.8:6544/Content/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTENTSERVICES_WSDL_LOCATION = url;
        CONTENTSERVICES_EXCEPTION = e;
    }

    public ContentServices() {
        super(__getWsdlLocation(), CONTENTSERVICES_QNAME);
    }

    public ContentServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTENTSERVICES_QNAME, features);
    }

    public ContentServices(URL wsdlLocation) {
        super(wsdlLocation, CONTENTSERVICES_QNAME);
    }

    public ContentServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTENTSERVICES_QNAME, features);
    }

    public ContentServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContentServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Content
     */
    @WebEndpoint(name = "BasicHttpBinding_Content")
    public Content getBasicHttpBindingContent() {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Content"), Content.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Content
     */
    @WebEndpoint(name = "BasicHttpBinding_Content")
    public Content getBasicHttpBindingContent(WebServiceFeature... features) {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Content"), Content.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTENTSERVICES_EXCEPTION!= null) {
            throw CONTENTSERVICES_EXCEPTION;
        }
        return CONTENTSERVICES_WSDL_LOCATION;
    }

}
